"""criar schema inicial

Revision ID: 037a3a17661c
Revises: 
Create Date: 2026-09-20 20:38:57.137031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '037a3a17661c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tabela', sa.String(length=100), nullable=False),
    sa.Column('operacao', sa.String(length=20), nullable=False),
    sa.Column('registro_id', sa.String(length=100), nullable=False),
    sa.Column('dados_anteriores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dados_novos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('executado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paroquia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('security_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('evento', sa.String(length=50), nullable=False),
    sa.Column('ip_origem', sa.String(length=45), nullable=True),
    sa.Column('detalhes', sa.String(length=255), nullable=True),
    sa.Column('executado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('igreja',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('is_matriz', sa.Boolean(), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('paroquia_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paroquia_id'], ['paroquia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('ADMINISTRADOR', 'DIZIMISTA', name='perfil_usuario_enum'), nullable=False),
    sa.Column('paroquia_id', sa.UUID(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paroquia_id'], ['paroquia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('consentimento_lgpd',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('aceito', sa.Boolean(), nullable=False),
    sa.Column('versao_termo', sa.String(length=10), nullable=False),
    sa.Column('aceito_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('notificacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('mensagem', sa.String(length=500), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('enviada_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfil_dizimista',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('igreja_id', sa.UUID(), nullable=False),
    sa.Column('status_cadastro', sa.Enum('PENDENTE', 'APROVADO', 'REJEITADO', name='status_cadastro_enum'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['igreja_id'], ['igreja.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('contribuicao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('perfil_dizimista_id', sa.UUID(), nullable=False),
    sa.Column('igreja_id', sa.UUID(), nullable=False),
    sa.Column('mes_referencia', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_registro', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['igreja_id'], ['igreja.id'], ),
    sa.ForeignKeyConstraint(['perfil_dizimista_id'], ['perfil_dizimista.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('perfil_dizimista_id', 'mes_referencia', name='uq_contribuicao_dizimista_mes')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contribuicao')
    op.drop_table('perfil_dizimista')
    op.drop_table('notificacao')
    op.drop_table('consentimento_lgpd')
    op.drop_table('usuario')
    op.drop_table('igreja')
    op.drop_table('security_log')
    op.drop_table('paroquia')
    op.drop_table('audit_log')
    # ### end Alembic commands ###

    # Remove os enums criados (autogenerate não faz isso automaticamente)
    sa.Enum(name='status_cadastro_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='perfil_usuario_enum').drop(op.get_bind(), checkfirst=True)
