"""adicionar endereco bairro cidade em perfil_dizimista e telefone data_nascimento em usuario

Revision ID: 9dc93ebfcb5b
Revises: 037a3a17661c
Create Date: 2026-09-22 00:33:21.861977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc93ebfcb5b'
down_revision: Union[str, Sequence[str], None] = '037a3a17661c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfil_dizimista', sa.Column('endereco', sa.String(length=255), nullable=True))
    op.add_column('perfil_dizimista', sa.Column('bairro', sa.String(length=100), nullable=True))
    op.add_column('perfil_dizimista', sa.Column('cidade', sa.String(length=100), nullable=True))
    op.add_column('usuario', sa.Column('telefone', sa.String(length=20), nullable=True))
    op.add_column('usuario', sa.Column('data_nascimento', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'data_nascimento')
    op.drop_column('usuario', 'telefone')
    op.drop_column('perfil_dizimista', 'cidade')
    op.drop_column('perfil_dizimista', 'bairro')
    op.drop_column('perfil_dizimista', 'endereco')
    # ### end Alembic commands ###
