"""remove tabela notificacao (RF09 fora de escopo)

Revision ID: b98a8b91d440
Revises: f6de8176fee5
Create Date: 2026-09-25 20:35:13.727499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b98a8b91d440'
down_revision: Union[str, Sequence[str], None] = 'f6de8176fee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacao',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mensagem', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('lida', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enviada_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('notificacao_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notificacao_pkey'))
    )
    # ### end Alembic commands ###
