"""add campos de bloqueio de conta em usuario

Revision ID: f6de8176fee5
Revises: 9dc93ebfcb5b
Create Date: 2026-09-25 20:17:06.468234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6de8176fee5'
down_revision: Union[str, Sequence[str], None] = '9dc93ebfcb5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('tentativas_falhas', sa.Integer(), nullable=False))
    op.add_column('usuario', sa.Column('bloqueado_até', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'bloqueado_até')
    op.drop_column('usuario', 'tentativas_falhas')
    # ### end Alembic commands ###
